const actionTypes = Object.freeze({
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",
  EDIT_USER_PROFILE_TOGGLE: "EDIT_USER_PROFILE_TOGGLE",
  EDIT_USER_PROFILE_SAVE: "EDIT_USER_PROFILE_SAVE",
});

export default actionTypes;
